### ISSUE TITLE
Git attribution history or complete changelog missing

### ISSUE THREAD

**Issue by sagredo-dev** [semhoun/qmailadmin#1]
It's a shame that you merged many thousands of rows of code from my repo and then forgot to import the changelog in order to give credit to people who contributed to the development of qmailadmin. 
Best thing would have been to fork my own repo and add to it the French translation and your autoresponder patch. You can find there the proper git attribution to the original authors.

**Comment by semhoun** [comment]
I'm sorry, It was not my purpose to steel or hide the work of anyone. It was just a projects I started long time ago (last modification was 2 years ago), and I want to test a new version of my s/qmail docker (it's still on DEV, and not commited).
If you watch my vpopmail project you could see, I forked the project and share my patch.
In my current dev for s/qmail docker, I already replace my vqadmin repo by yours.
I planned to also replace this repo by yours, and just apply a patch (and maybe make a pull request, If I made a version compatible with autorespond and qmailrespond).
I hope you will understand, It was just a quick patch/copy/past before making things clean.
